#!/usr/bin/env python3
"""
2025 HLT re-emulation (L1REPACK/uGT + HLT GRun menu) launcher for DQCD Run3
production.

Takes a hardcoded list of published RAWSIM input datasets (see HLT_DATASETS
in main() below), reuses the shared cfg already produced in
hlt_re-emulation/reHLT_mc_2025.py -- the step doesn't depend on the sample,
only on the input dataset that CRAB substitutes at runtime, so one cfg covers
every submission -- writes a CRAB config per sample, and submits.

hlt_re-emulation/reHLT_mc_2025.py was generated with hltGetConfiguration
(see README.md, section "2025 reL1 and HLT") and already has
process.maxEvents.input = -1, so -- unlike chain/rawsim_cfg.py -- this script
does not need to patch maxEvents. It still copies the cfg into a single
self-contained pset (<work-area>/reHLT_mc_2025_cfg.py) instead of pointing
CRAB straight at hlt_re-emulation/reHLT_mc_2025.py, so every sample's sandbox
is built from an identical, untouched snapshot of the cfg.

IMPORTANT: unlike the GEN-SIM/RAWSIM steps (CMSSW_17_0_0_pre2), this step
must run from a CMSSW_15_0_15_patch1 area -- the cfg was produced by
hltGetConfiguration against the HLT menu/table shipped in that release, and
won't resolve under a different one:

  export SCRAM_ARCH=el8_amd64_gcc13
  source /cvmfs/cms.cern.ch/cmsset_default.sh
  cmsrel CMSSW_15_0_15_patch1
  cd CMSSW_15_0_15_patch1/src
  cmsenv

Assumes:
  - CRAB env is set up (source /cvmfs/cms.cern.ch/crab3/crab.sh)
  - The RAWSIM samples were already submitted+published with submit_rawsim.py
  - hlt_re-emulation/reHLT_mc_2025.py exists (see README.md if it needs
    regenerating)

Usage:
  python3 submit_25hlt.py [options]
  python3 submit_25hlt.py --dry-run
  python3 submit_25hlt.py --filter ScenarioA

  # Test the submission without launching real grid jobs: validates the CRAB
  # config/pset and builds the sandbox, then lets you run one job locally
  # (crab preparelocal) against a real input file from the dataset. Use a
  # throwaway --work-area so this doesn't mark the sample as "already
  # submitted" for a later real run.
  python3 submit_25hlt.py --crab-dryrun --work-area crab_25hlt_test --filter ScenarioA
"""

import argparse
import os
import subprocess
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Defaults -- override via CLI flags
# ---------------------------------------------------------------------------
CHAIN_CFG = Path(__file__).resolve().parent.parent / "hlt_re-emulation" / "reHLT_mc_2025.py"
REQUIRED_CMSSW_RELEASE = "CMSSW_15_0_15_patch1"

CRAB_TEMPLATE = """\
from CRABClient.UserUtilities import config
config = config()

config.General.requestName = '{name}_HLT2025'
config.General.workArea = '{work_area}'
config.General.transferOutputs = True
config.General.transferLogs = True

config.JobType.pluginName = 'Analysis'
config.JobType.psetName = '{cfg}'
config.JobType.maxMemoryMB = {max_memory_mb}
config.JobType.numCores = {num_cores}

config.Data.inputDataset = '{input_dataset}'
config.Data.splitting = 'FileBased'
config.Data.unitsPerJob = {files_per_job}
config.Data.totalUnits = -1
config.Data.outLFNDirBase = '{lfn_base}'
config.Data.publication = True
config.Data.outputDatasetTag = '{tag}'
config.Data.ignoreLocality = True
config.Data.inputDBS = 'phys03'

config.Site.storageSite = '{site}'
config.Site.blacklist = ['T2_US_MIT']
config.Site.whitelist = ['T2_US_Wisconsin','T2_US_Florida','T2_US_Nebraska','T2_US_Caltech','T2_US_Purdue', 'T2_US_UCSD']

config.section_("Debug")
config.Debug.extraJDL = ['My.CMS_ALLOW_OVERFLOW=False']
"""


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def run(cmd: str, cwd: Path, dry_run: bool) -> None:
    print(f"    $ {cmd}")
    if dry_run:
        return
    result = subprocess.run(cmd, shell=True, cwd=cwd)
    if result.returncode != 0:
        raise RuntimeError(f"Command exited with code {result.returncode}")


def check_cmssw_release(dry_run: bool) -> None:
    """The cfg was generated by hltGetConfiguration against the HLT menu
    shipped in REQUIRED_CMSSW_RELEASE; running it from another release can
    silently pick up a different (incompatible) HLT menu/table."""
    version = os.environ.get("CMSSW_VERSION")
    if version == REQUIRED_CMSSW_RELEASE:
        return
    msg = (
        f"CMSSW_VERSION is '{version}', expected '{REQUIRED_CMSSW_RELEASE}'.\n"
        f"       cmsenv from a {REQUIRED_CMSSW_RELEASE}/src area before submitting "
        f"(see README.md, section \"2025 reL1 and HLT\")."
    )
    if dry_run:
        print(f"WARNING: {msg}")
    else:
        sys.exit(f"ERROR: {msg}")


def is_already_submitted(work_area: Path, name: str) -> bool:
    """CRAB creates crab_<name>_HLT2025/ inside workArea after a successful submit."""
    return (work_area / name / f"crab_{name}_HLT2025").exists()


def build_shared_cfg(chain_cfg: Path, work_area: Path, dry_run: bool) -> Path:
    """Copy chain_cfg into a single self-contained pset, shared by every
    sample (the HLT re-emulation step doesn't read anything sample-specific).
    Unlike chain/rawsim_cfg.py, this cfg already has maxEvents.input = -1, so
    no override is appended."""
    if not chain_cfg.is_file():
        sys.exit(f"ERROR: cfg not found at {chain_cfg} (see README.md to regenerate it)")

    cfg = work_area / "reHLT_mc_2025_cfg.py"
    print(f"    $ cp {chain_cfg} -> {cfg}")
    if not dry_run:
        cfg.write_text(chain_cfg.read_text())
    return cfg


def write_crab_config(name: str, cfg: Path, job_dir: Path, work_area: Path,
                      input_dataset: str, files_per_job: int, lfn_base: str,
                      tag: str, site: str, max_memory_mb: int, num_cores: int,
                      dry_run: bool) -> Path:
    crab_cfg = job_dir / f"crab_{name}_hlt2025.py"
    print(f"    $ write {crab_cfg}")
    if not dry_run:
        crab_cfg.write_text(CRAB_TEMPLATE.format(
            name=name,
            work_area=str(work_area),
            cfg=str(cfg),
            input_dataset=input_dataset,
            files_per_job=files_per_job,
            lfn_base=lfn_base,
            tag=tag,
            site=site,
            max_memory_mb=max_memory_mb,
            num_cores=num_cores,
        ))
    return crab_cfg


def crab_submit(name: str, crab_cfg: Path, job_dir: Path, dry_run: bool, crab_dryrun: bool) -> None:
    flag = " --dryrun" if crab_dryrun else ""
    run(f"crab submit{flag} {crab_cfg}", cwd=job_dir, dry_run=dry_run)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def parse_args():
    p = argparse.ArgumentParser(
        description="Submit 2025 HLT re-emulation CRAB jobs for DQCD Run3 production.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    p.add_argument(
        "--chain-cfg", type=Path, default=CHAIN_CFG,
        help="Path to the already-generated hltGetConfiguration cfg to reuse for every sample",
    )
    p.add_argument(
        "--filter", type=str, default=None, metavar="STR",
        help="Only process samples whose name contains STR (e.g. 'ScenarioA')",
    )
    p.add_argument(
        "--work-area", type=str, default="crab_25hlt",
        help="CRAB workArea directory (created if absent)",
    )
    p.add_argument(
        "--files-per-job", type=int, default=1,
        help="Input files per CRAB job (Data.unitsPerJob under FileBased splitting)",
    )
    p.add_argument(
        "--lfn-base", type=str, default="/store/user/fernance/FinalScoutingProduction/HLT/",
        help="LFN output base path on the storage element",
    )
    p.add_argument(
        "--site", type=str, default="T2_US_UCSD",
        help="CMS storage site for output",
    )
    p.add_argument(
        "--tag", type=str, default="hlt_2025_v0",
        help="CRAB outputDatasetTag for the HLT re-emulation output",
    )
    p.add_argument(
        "--max-memory-mb", type=int, default=3000,
        help="config.JobType.maxMemoryMB (the full HLT menu + L1 emulator need more than the RAWSIM step)",
    )
    p.add_argument(
        "--num-cores", type=int, default=1,
        help="config.JobType.numCores (matches process.options.numberOfThreads=1 set in the cfg)",
    )
    p.add_argument(
        "--dry-run", action="store_true",
        help="Print all commands without executing anything",
    )
    p.add_argument(
        "--crab-dryrun", action="store_true",
        help=(
            "Pass --dryrun through to 'crab submit': validates the config and builds "
            "the sandbox/pset without launching real grid jobs. Follow up with "
            "'crab preparelocal -d <crab_..._HLT2025 dir>' to run one job locally. "
            "Use a separate --work-area so the sample isn't marked as already "
            "submitted for a later real run."
        ),
    )
    return p.parse_args()


def main():
    # Hardcoded (name -> published RAWSIM input dataset) list. Fill in the
    # exact DAS path once submit_rawsim.py's samples have finished and been
    # published, e.g.:
    #   dasgoclient -query="dataset dataset=/<name>/*rawsim_2024_v0*/GEN-SIM-RAW"
    HLT_DATASETS: dict[str, str] = {
        "GluGluHToDarkShowers-ScenarioA_Par-ctau-10-mA-1p67-mpi-5":
            "/GluGluHToDarkShowers-ScenarioA_Par-ctau-10-mA-1p67-mpi-5/fernance-rawsim_2024_v0-f6f3088a6fb92bcbff788017883cfd56/USER",
    }

    args = parse_args()

    check_cmssw_release(args.dry_run)

    names = [n for n in HLT_DATASETS if not args.filter or args.filter in n]
    if not names:
        sys.exit(
            "ERROR: No samples in HLT_DATASETS"
            + (f" matching '{args.filter}'" if args.filter else "")
        )

    for name in names:
        if "REPLACE_WITH_PUBLISHED_HASH" in HLT_DATASETS[name]:
            sys.exit(
                f"ERROR: HLT_DATASETS['{name}'] is still a placeholder.\n"
                f"       Look up the published RAWSIM dataset with:\n"
                f"       dasgoclient -query=\"dataset dataset=/{name}/*/GEN-SIM-RAW\"\n"
                f"       and hardcode the full result in HLT_DATASETS in this script."
            )

    work_area = Path(args.work_area).resolve()
    if not args.dry_run:
        work_area.mkdir(parents=True, exist_ok=True)

    label = "[DRY-RUN] " if args.dry_run else ""
    print(f"{label}Processing {len(names)} sample(s)\n")

    print("Building shared HLT re-emulation cfg (reused for every sample):")
    cfg = build_shared_cfg(args.chain_cfg, work_area, args.dry_run)
    print()

    n_ok = n_skip = n_fail = 0

    for name in names:
        if is_already_submitted(work_area, name):
            print(f"  [SKIP]   {name}")
            n_skip += 1
            continue

        print(f"  [SUBMIT] {name}")
        job_dir = work_area / name
        if not args.dry_run:
            job_dir.mkdir(parents=True, exist_ok=True)

        try:
            crab_cfg = write_crab_config(
                name=name,
                cfg=cfg,
                job_dir=job_dir,
                work_area=work_area,
                input_dataset=HLT_DATASETS[name],
                files_per_job=args.files_per_job,
                lfn_base=args.lfn_base,
                tag=args.tag,
                site=args.site,
                max_memory_mb=args.max_memory_mb,
                num_cores=args.num_cores,
                dry_run=args.dry_run,
            )
            crab_submit(name, crab_cfg, job_dir, args.dry_run, args.crab_dryrun)
            n_ok += 1
        except Exception as exc:
            print(f"    ERROR: {exc}", file=sys.stderr)
            n_fail += 1

    print(f"\nDone -- submitted: {n_ok}  skipped: {n_skip}  failed: {n_fail}")
    if n_fail:
        sys.exit(1)


if __name__ == "__main__":
    main()
