#!/usr/bin/env python3
"""
RAWSIM (DIGI,DATAMIX,L1,DIGI2RAW premix) launcher for DQCD Run3 2024 production.

Takes a hardcoded list of published GEN-SIM input datasets (see RAWSIM_DATASETS
in main() below), reuses the shared DIGI/RAW cfg already produced in
chain/rawsim_cfg.py -- the step doesn't depend on the sample, only on the
input dataset that CRAB substitutes at runtime, so one cfg covers every
submission -- writes a CRAB config per sample, and submits.

chain/rawsim_cfg.py was generated by cmsDriver for a local test with
--number 100, so process.maxEvents.input is hardcoded to 100 in that file.
This script never edits chain/rawsim_cfg.py in place; instead it copies its
content into a single self-contained pset (<work-area>/rawsim_cfg.py) with
process.maxEvents.input reset to -1, so every CRAB job processes -- and
writes -- every event in its assigned input file(s) instead of stopping
after 100. Combined with FileBased splitting and Data.totalUnits = -1 (all
files), this guarantees every event of each GEN-SIM dataset ends up in the
RAWSIM output.

Assumes:
  - CRAB env is set up (source /cvmfs/cms.cern.ch/crab3/crab.sh)
  - The GEN-SIM samples were already submitted+published with submit_gensim.py
  - chain/rawsim_cfg.py exists (produced once via cmsDriver, see README.md)

Usage:
  python3 submit_rawsim.py [options]
  python3 submit_rawsim.py --dry-run
  python3 submit_rawsim.py --filter ScenarioA

  # Test the submission without launching real grid jobs: validates the CRAB
  # config/pset and builds the sandbox, then lets you run one job locally
  # (crab preparelocal) against a real input file from the dataset. Use a
  # throwaway --work-area so this doesn't mark the sample as "already
  # submitted" for a later real run.
  python3 submit_rawsim.py --crab-dryrun --work-area crab_rawsim_test --filter ScenarioA
"""

import argparse
import subprocess
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Defaults -- override via CLI flags
# ---------------------------------------------------------------------------
CHAIN_CFG = Path(__file__).resolve().parent.parent / "chain" / "rawsim_cfg.py"

MAXEVENTS_OVERRIDE = """
# --- override appended by submit_rawsim.py ------------------------------
# chain/rawsim_cfg.py above was generated locally with --number 100; reset
# to -1 here so CRAB processes (and writes) every event in each job's
# assigned input file(s) instead of stopping after 100.
process.maxEvents.input = cms.untracked.int32(-1)
"""

CRAB_TEMPLATE = """\
from CRABClient.UserUtilities import config
config = config()

config.General.requestName = '{name}_RAWSIM'
config.General.workArea = '{work_area}'
config.General.transferOutputs = True
config.General.transferLogs = True

config.JobType.pluginName = 'Analysis'
config.JobType.psetName = '{cfg}'
config.JobType.maxMemoryMB = 3000
config.JobType.numCores = 1

config.Data.inputDataset = '{input_dataset}'
config.Data.splitting = 'FileBased'
config.Data.unitsPerJob = {files_per_job}
config.Data.totalUnits = -1
config.Data.outLFNDirBase = '{lfn_base}'
config.Data.publication = True
config.Data.outputDatasetTag = '{tag}'
config.Data.ignoreLocality = True
config.Data.inputDBS = 'phys03'

config.Site.storageSite = '{site}'
config.Site.blacklist = ['T2_US_MIT']
config.Site.whitelist = ['T2_US_Wisconsin','T2_US_Florida','T2_US_Nebraska','T2_US_Caltech','T2_US_Purdue', 'T2_US_UCSD']

config.section_("Debug")
config.Debug.extraJDL = ['My.CMS_ALLOW_OVERFLOW=False']
"""


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def run(cmd: str, cwd: Path, dry_run: bool) -> None:
    print(f"    $ {cmd}")
    if dry_run:
        return
    result = subprocess.run(cmd, shell=True, cwd=cwd)
    if result.returncode != 0:
        raise RuntimeError(f"Command exited with code {result.returncode}")


def is_already_submitted(work_area: Path, name: str) -> bool:
    """CRAB creates crab_<name>_RAWSIM/ inside workArea after a successful submit."""
    return (work_area / name / f"crab_{name}_RAWSIM").exists()


def build_shared_cfg(chain_cfg: Path, work_area: Path, dry_run: bool) -> Path:
    """Copy chain_cfg into a single self-contained pset, shared by every
    sample (the DIGI/RAW step doesn't read anything sample-specific), with
    maxEvents.input reset to -1 so CRAB jobs process every event."""
    if not chain_cfg.is_file():
        sys.exit(f"ERROR: cfg not found at {chain_cfg} (see README.md to regenerate it)")

    cfg = work_area / "rawsim_cfg.py"
    print(f"    $ cp {chain_cfg} -> {cfg}  (+ maxEvents.input = -1 override)")
    if not dry_run:
        cfg.write_text(chain_cfg.read_text() + MAXEVENTS_OVERRIDE)
    return cfg


def write_crab_config(name: str, cfg: Path, job_dir: Path, work_area: Path,
                      input_dataset: str, files_per_job: int, lfn_base: str,
                      tag: str, site: str, dry_run: bool) -> Path:
    crab_cfg = job_dir / f"crab_{name}_rawsim.py"
    print(f"    $ write {crab_cfg}")
    if not dry_run:
        crab_cfg.write_text(CRAB_TEMPLATE.format(
            name=name,
            work_area=str(work_area),
            cfg=str(cfg),
            input_dataset=input_dataset,
            files_per_job=files_per_job,
            lfn_base=lfn_base,
            tag=tag,
            site=site,
        ))
    return crab_cfg


def crab_submit(name: str, crab_cfg: Path, job_dir: Path, dry_run: bool, crab_dryrun: bool) -> None:
    flag = " --dryrun" if crab_dryrun else ""
    run(f"crab submit{flag} {crab_cfg}", cwd=job_dir, dry_run=dry_run)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def parse_args():
    p = argparse.ArgumentParser(
        description="Submit RAWSIM (DIGI/DATAMIX/L1/DIGI2RAW premix) CRAB jobs for DQCD Run3 2024 production.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    p.add_argument(
        "--chain-cfg", type=Path, default=CHAIN_CFG,
        help="Path to the already-generated DIGI/RAW cmsDriver cfg to reuse for every sample",
    )
    p.add_argument(
        "--filter", type=str, default=None, metavar="STR",
        help="Only process samples whose name contains STR (e.g. 'ScenarioA')",
    )
    p.add_argument(
        "--work-area", type=str, default="crab_rawsim",
        help="CRAB workArea directory (created if absent)",
    )
    p.add_argument(
        "--files-per-job", type=int, default=1,
        help="Input files per CRAB job (Data.unitsPerJob under FileBased splitting)",
    )
    p.add_argument(
        "--lfn-base", type=str, default="/store/user/fernance/FinalScoutingProduction/GEN-SIM-RAW/",
        help="LFN output base path on the storage element",
    )
    p.add_argument(
        "--site", type=str, default="T2_US_UCSD",
        help="CMS storage site for output",
    )
    p.add_argument(
        "--tag", type=str, default="rawsim_2024_v0",
        help="CRAB outputDatasetTag for the RAWSIM output",
    )
    p.add_argument(
        "--dry-run", action="store_true",
        help="Print all commands without executing anything",
    )
    p.add_argument(
        "--crab-dryrun", action="store_true",
        help=(
            "Pass --dryrun through to 'crab submit': validates the config and builds "
            "the sandbox/pset without launching real grid jobs. Follow up with "
            "'crab preparelocal -d <crab_..._RAWSIM dir>' to run one job locally. "
            "Use a separate --work-area so the sample isn't marked as already "
            "submitted for a later real run."
        ),
    )
    return p.parse_args()


def main():
    # Hardcoded (name -> published GEN-SIM input dataset) list. Fill in the
    # exact DAS path once submit_gensim.py's samples have finished and been
    # published, e.g.:
    #   dasgoclient -query="dataset dataset=/<name>/*gensim_2024_v0*/GEN-SIM"
    RAWSIM_DATASETS: dict[str, str] = {
        "GluGluHToDarkShowers-ScenarioA_Par-ctau-10-mA-1p67-mpi-5":
            "/GluGluHToDarkShowers-ScenarioA_Par-ctau-10-mA-1p67-mpi-5/"
            "fernance-gensim_2024_v0-06e774f08b815cbdd012a58a604c4a73/USER",
    }

    args = parse_args()

    names = [n for n in RAWSIM_DATASETS if not args.filter or args.filter in n]
    if not names:
        sys.exit(
            "ERROR: No samples in RAWSIM_DATASETS"
            + (f" matching '{args.filter}'" if args.filter else "")
        )

    for name in names:
        if "REPLACE_WITH_PUBLISHED_HASH" in RAWSIM_DATASETS[name]:
            sys.exit(
                f"ERROR: RAWSIM_DATASETS['{name}'] is still a placeholder.\n"
                f"       Look up the published GEN-SIM dataset with:\n"
                f"       dasgoclient -query=\"dataset dataset=/{name}/*/GEN-SIM\"\n"
                f"       and hardcode the full result in RAWSIM_DATASETS in this script."
            )

    work_area = Path(args.work_area).resolve()
    if not args.dry_run:
        work_area.mkdir(parents=True, exist_ok=True)

    label = "[DRY-RUN] " if args.dry_run else ""
    print(f"{label}Processing {len(names)} sample(s)\n")

    print("Building shared DIGI/RAW cfg (reused for every sample):")
    cfg = build_shared_cfg(args.chain_cfg, work_area, args.dry_run)
    print()

    n_ok = n_skip = n_fail = 0

    for name in names:
        if is_already_submitted(work_area, name):
            print(f"  [SKIP]   {name}")
            n_skip += 1
            continue

        print(f"  [SUBMIT] {name}")
        job_dir = work_area / name
        if not args.dry_run:
            job_dir.mkdir(parents=True, exist_ok=True)

        try:
            crab_cfg = write_crab_config(
                name=name,
                cfg=cfg,
                job_dir=job_dir,
                work_area=work_area,
                input_dataset=RAWSIM_DATASETS[name],
                files_per_job=args.files_per_job,
                lfn_base=args.lfn_base,
                tag=args.tag,
                site=args.site,
                dry_run=args.dry_run,
            )
            crab_submit(name, crab_cfg, job_dir, args.dry_run, args.crab_dryrun)
            n_ok += 1
        except Exception as exc:
            print(f"    ERROR: {exc}", file=sys.stderr)
            n_fail += 1

    print(f"\nDone -- submitted: {n_ok}  skipped: {n_skip}  failed: {n_fail}")
    if n_fail:
        sys.exit(1)


if __name__ == "__main__":
    main()
